apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: gcp-time-api  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: api  
  template:  
    metadata:  
      labels:  
        app: api  
    spec:  
      containers:  
      - name: gcp-time-api  
        image: us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/gcp-time-api-repo/gcp-time-api:latest  
        ports:  
        - containerPort: 8080  
        env:  
          - name: PORT  
            value: "8080"  
        resources:  
          requests:  
            memory: "1Gi"  
            cpu: "500m"  
          limits:  
            memory: "1Gi"  
            cpu: "500m"