name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Set up Google Cloud CLI  
        uses: google-github-actions/setup-gcloud@v1  
        with:  
          project_id: ${{ secrets.GCP_PROJECT_ID }}  
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  
          export_default_credentials: true  

      - name: Configure Terraform  
        run: |  
          cd terraform  
          terraform init  
          terraform apply -auto-approve  

      - name: Build Docker image  
        run: |  
          cd api  
          docker build -t ${{ secrets.GCP_PROJECT_ID }}/gcp-time-api:latest .  
          docker push ${{ secrets.GCP_PROJECT_ID }}/gcp-time-api:latest 