name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Set up Google Cloud CLI  
        uses: google-github-actions/setup-gcloud@v1  
        with:  
          project_id: ${{ secrets.GCP_PROJECT_ID }}  
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  
          export_default_credentials: true  

      - name: Configure Terraform  
        run: |  
          cd terraform  
          terraform init  
          terraform apply -auto-approve  

      - name: Build Docker image  
        run: |  
          cd api  
          docker build -t ${{ secrets.GCP_PROJECT_ID }}/gcp-time-api:latest .  
          docker push ${{ secrets.GCP_PROJECT_ID }}/gcp-time-api:latest  

      - name: Test API  
        run: |  
          sleep 30 # Wait for the API to be up  
          RESPONSE=$(curl --write-out "%{http_code}\n" --silent --output /dev/null http://${{ outputs.k8s_cluster_endpoint }}/current_time)  
          if [ "$RESPONSE" -ne "200" ]; then  
            echo "API is not accessible. HTTP response code: $RESPONSE"  
            exit 1  
          fi  
          echo "API is successfully accessible."